package Modelo;
// Generated 19-mar-2018 13:26:03 by Hibernate Tools 4.3.1

import java.sql.Time;

/**
 * Coche generated by hbm2java
 */
public class Coche implements java.io.Serializable {

    private Integer id;
    private String matricula;
    private String modelo;
    private Time horaEntrada;
    private Time horaSalida;
    private int tiempoPermitido;

    public Coche() {
    }

    public Coche(String matricula, String modelo, Time horaEntrada, Time horaSalida, int tiempoPermitido) {
        this.matricula = matricula;
        this.modelo = modelo;
        this.horaEntrada = horaEntrada;
        this.horaSalida = horaSalida;
        this.tiempoPermitido = tiempoPermitido;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMatricula() {
        return this.matricula;
    }
    
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    
    
    public String getModelo() {
        return this.modelo;
    }

    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public Time getHoraEntrada() {
        return this.horaEntrada;
    }

  
    public void setHoraEntrada(Time horaEntrada) {
        this.horaEntrada = horaEntrada;
    }

    public Time getHoraSalida() {
        return this.horaSalida;
    }

    public void setHoraSalida(Time horaSalida) {
        this.horaSalida = horaSalida;
    }

    public int getTiempoPermitido() {
        return this.tiempoPermitido;
    }


    public void setTiempoPermitido(int tiempoPermitido) {
        this.tiempoPermitido = tiempoPermitido;
    }

    public boolean esSuperado() {
        boolean superado = false;
        if ((this.getHoraEntrada().getTime() + this.getTiempoPermitido() * 60000) < this.getHoraSalida().getTime()) {
            superado = true;
        }
        return superado;
    }

}
