package libreria;
// Generated 10-mar-2018 4:04:03 by Hibernate Tools 4.3.1



/**
 * Editorial generated by hbm2java
 */
public class Editorial  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public Editorial() {
    }

    public Editorial(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


