package libros;
// Generated 17-abr-2018 11:09:19 by Hibernate Tools 4.3.1



/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private int id;
     private String autor;
     private String titulo;
     private float precio;
     private int isbn;

    public Libro() {
    }

    public Libro(int id, String autor, String titulo, float precio, int isbn) {
       this.id = id;
       this.autor = autor;
       this.titulo = titulo;
       this.precio = precio;
       this.isbn = isbn;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }




}


