package modelo;
// Generated 27-abr-2018 5:50:38 by Hibernate Tools 4.3.1



/**
 * FotoVehi generated by hbm2java
 */
public class FotoVehi  implements java.io.Serializable {


     private Integer idFotoVehi;
     private Vehiculo vehiculo;
     private String rutaFoto;

    public FotoVehi() {
    }

    public FotoVehi(Vehiculo vehiculo, String rutaFoto) {
       this.vehiculo = vehiculo;
       this.rutaFoto = rutaFoto;
    }
   
    public Integer getIdFotoVehi() {
        return this.idFotoVehi;
    }
    
    public void setIdFotoVehi(Integer idFotoVehi) {
        this.idFotoVehi = idFotoVehi;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getRutaFoto() {
        return this.rutaFoto;
    }
    
    public void setRutaFoto(String rutaFoto) {
        this.rutaFoto = rutaFoto;
    }




}


