package modelo;
// Generated 27-abr-2018 5:50:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private Integer idLocalidad;
     private Provincia provincia;
     private String nombre;
     private Set viajesForIdLocalidadDestino = new HashSet(0);
     private Set viajesForIdLocalidadOrigen = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(Provincia provincia, String nombre) {
        this.provincia = provincia;
        this.nombre = nombre;
    }
    public Localidad(Provincia provincia, String nombre, Set viajesForIdLocalidadDestino, Set viajesForIdLocalidadOrigen) {
       this.provincia = provincia;
       this.nombre = nombre;
       this.viajesForIdLocalidadDestino = viajesForIdLocalidadDestino;
       this.viajesForIdLocalidadOrigen = viajesForIdLocalidadOrigen;
    }
   
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getViajesForIdLocalidadDestino() {
        return this.viajesForIdLocalidadDestino;
    }
    
    public void setViajesForIdLocalidadDestino(Set viajesForIdLocalidadDestino) {
        this.viajesForIdLocalidadDestino = viajesForIdLocalidadDestino;
    }
    public Set getViajesForIdLocalidadOrigen() {
        return this.viajesForIdLocalidadOrigen;
    }
    
    public void setViajesForIdLocalidadOrigen(Set viajesForIdLocalidadOrigen) {
        this.viajesForIdLocalidadOrigen = viajesForIdLocalidadOrigen;
    }




}


