package modelo;
// Generated 27-abr-2018 5:50:38 by Hibernate Tools 4.3.1



/**
 * Pasajeros generated by hbm2java
 */
public class Pasajeros  implements java.io.Serializable {


     private PasajerosId id;
     private Usuario usuario;
     private Viaje viaje;

    public Pasajeros() {
    }

    public Pasajeros(PasajerosId id, Usuario usuario, Viaje viaje) {
       this.id = id;
       this.usuario = usuario;
       this.viaje = viaje;
    }
   
    public PasajerosId getId() {
        return this.id;
    }
    
    public void setId(PasajerosId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }




}


