package modelo;
// Generated 27-abr-2018 5:50:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Integer idVehiculo;
     private Usuario usuario;
     private String marca;
     private String modelo;
     private String color;
     private int plazas;
     private Set viajes = new HashSet(0);
     private Set fotoVehis = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(Usuario usuario, String marca, String modelo, String color, int plazas) {
        this.usuario = usuario;
        this.marca = marca;
        this.modelo = modelo;
        this.color = color;
        this.plazas = plazas;
    }
    public Vehiculo(Usuario usuario, String marca, String modelo, String color, int plazas, Set viajes, Set fotoVehis) {
       this.usuario = usuario;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.plazas = plazas;
       this.viajes = viajes;
       this.fotoVehis = fotoVehis;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(int plazas) {
        this.plazas = plazas;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }
    public Set getFotoVehis() {
        return this.fotoVehis;
    }
    
    public void setFotoVehis(Set fotoVehis) {
        this.fotoVehis = fotoVehis;
    }




}


