package modelo;
// Generated 27-abr-2018 5:50:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer idViaje;
     private Localidad localidadByIdLocalidadDestino;
     private Localidad localidadByIdLocalidadOrigen;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private String puntoRecogida;
     private int plazasMax;
     private double percioPersona;
     private Date fechaHoraSalida;
     private Set pasajeroses = new HashSet(0);

    public Viaje() {
    }

	
    public Viaje(Localidad localidadByIdLocalidadDestino, Localidad localidadByIdLocalidadOrigen, Usuario usuario, Vehiculo vehiculo, String puntoRecogida, int plazasMax, double percioPersona, Date fechaHoraSalida) {
        this.localidadByIdLocalidadDestino = localidadByIdLocalidadDestino;
        this.localidadByIdLocalidadOrigen = localidadByIdLocalidadOrigen;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.puntoRecogida = puntoRecogida;
        this.plazasMax = plazasMax;
        this.percioPersona = percioPersona;
        this.fechaHoraSalida = fechaHoraSalida;
    }
    public Viaje(Localidad localidadByIdLocalidadDestino, Localidad localidadByIdLocalidadOrigen, Usuario usuario, Vehiculo vehiculo, String puntoRecogida, int plazasMax, double percioPersona, Date fechaHoraSalida, Set pasajeroses) {
       this.localidadByIdLocalidadDestino = localidadByIdLocalidadDestino;
       this.localidadByIdLocalidadOrigen = localidadByIdLocalidadOrigen;
       this.usuario = usuario;
       this.vehiculo = vehiculo;
       this.puntoRecogida = puntoRecogida;
       this.plazasMax = plazasMax;
       this.percioPersona = percioPersona;
       this.fechaHoraSalida = fechaHoraSalida;
       this.pasajeroses = pasajeroses;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public Localidad getLocalidadByIdLocalidadDestino() {
        return this.localidadByIdLocalidadDestino;
    }
    
    public void setLocalidadByIdLocalidadDestino(Localidad localidadByIdLocalidadDestino) {
        this.localidadByIdLocalidadDestino = localidadByIdLocalidadDestino;
    }
    public Localidad getLocalidadByIdLocalidadOrigen() {
        return this.localidadByIdLocalidadOrigen;
    }
    
    public void setLocalidadByIdLocalidadOrigen(Localidad localidadByIdLocalidadOrigen) {
        this.localidadByIdLocalidadOrigen = localidadByIdLocalidadOrigen;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getPuntoRecogida() {
        return this.puntoRecogida;
    }
    
    public void setPuntoRecogida(String puntoRecogida) {
        this.puntoRecogida = puntoRecogida;
    }
    public int getPlazasMax() {
        return this.plazasMax;
    }
    
    public void setPlazasMax(int plazasMax) {
        this.plazasMax = plazasMax;
    }
    public double getPercioPersona() {
        return this.percioPersona;
    }
    
    public void setPercioPersona(double percioPersona) {
        this.percioPersona = percioPersona;
    }
    public Date getFechaHoraSalida() {
        return this.fechaHoraSalida;
    }
    
    public void setFechaHoraSalida(Date fechaHoraSalida) {
        this.fechaHoraSalida = fechaHoraSalida;
    }
    public Set getPasajeroses() {
        return this.pasajeroses;
    }
    
    public void setPasajeroses(Set pasajeroses) {
        this.pasajeroses = pasajeroses;
    }




}


