package profesores;
// Generated 29-mar-2018 16:59:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellidos;
     private Date fechaAlta;
     private String departamento;

    public Profesor() {
    }

    public Profesor(String dni, String nombre, String apellidos, Date fechaAlta, String departamento) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaAlta = fechaAlta;
       this.departamento = departamento;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }




}


