package POJOs;
// Generated 13-may-2018 13:13:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private Usuario usuarioByIdUsuarioRecibe;
     private Usuario usuarioByIdUsuarioEnvia;
     private String texto;
     private Date fechaHora;

    public Mensaje() {
    }

    public Mensaje(Usuario usuarioByIdUsuarioRecibe, Usuario usuarioByIdUsuarioEnvia, String texto, Date fechaHora) {
       this.usuarioByIdUsuarioRecibe = usuarioByIdUsuarioRecibe;
       this.usuarioByIdUsuarioEnvia = usuarioByIdUsuarioEnvia;
       this.texto = texto;
       this.fechaHora = fechaHora;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Usuario getUsuarioByIdUsuarioRecibe() {
        return this.usuarioByIdUsuarioRecibe;
    }
    
    public void setUsuarioByIdUsuarioRecibe(Usuario usuarioByIdUsuarioRecibe) {
        this.usuarioByIdUsuarioRecibe = usuarioByIdUsuarioRecibe;
    }
    public Usuario getUsuarioByIdUsuarioEnvia() {
        return this.usuarioByIdUsuarioEnvia;
    }
    
    public void setUsuarioByIdUsuarioEnvia(Usuario usuarioByIdUsuarioEnvia) {
        this.usuarioByIdUsuarioEnvia = usuarioByIdUsuarioEnvia;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }




}


