package POJOs;
// Generated 13-may-2018 13:13:31 by Hibernate Tools 4.3.1



/**
 * PasajerosId generated by hbm2java
 */
public class PasajerosId  implements java.io.Serializable {


     private int idUsuario;
     private int idViaje;

    public PasajerosId() {
    }

    public PasajerosId(int idUsuario, int idViaje) {
       this.idUsuario = idUsuario;
       this.idViaje = idViaje;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(int idViaje) {
        this.idViaje = idViaje;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PasajerosId) ) return false;
		 PasajerosId castOther = ( PasajerosId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdViaje()==castOther.getIdViaje());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdViaje();
         return result;
   }   


}


