package POJOs;
// Generated 13-may-2018 13:13:31 by Hibernate Tools 4.3.1



/**
 * Puntuacion generated by hbm2java
 */
public class Puntuacion  implements java.io.Serializable {


     private Integer idPuntuacion;
     private Usuario usuarioByIdUsuarioPuntua;
     private Usuario usuarioByIdUsuarioRecibe;
     private int puntuacion;
     private String comentario;

    public Puntuacion() {
    }

    public Puntuacion(Usuario usuarioByIdUsuarioPuntua, Usuario usuarioByIdUsuarioRecibe, int puntuacion, String comentario) {
       this.usuarioByIdUsuarioPuntua = usuarioByIdUsuarioPuntua;
       this.usuarioByIdUsuarioRecibe = usuarioByIdUsuarioRecibe;
       this.puntuacion = puntuacion;
       this.comentario = comentario;
    }
   
    public Integer getIdPuntuacion() {
        return this.idPuntuacion;
    }
    
    public void setIdPuntuacion(Integer idPuntuacion) {
        this.idPuntuacion = idPuntuacion;
    }
    public Usuario getUsuarioByIdUsuarioPuntua() {
        return this.usuarioByIdUsuarioPuntua;
    }
    
    public void setUsuarioByIdUsuarioPuntua(Usuario usuarioByIdUsuarioPuntua) {
        this.usuarioByIdUsuarioPuntua = usuarioByIdUsuarioPuntua;
    }
    public Usuario getUsuarioByIdUsuarioRecibe() {
        return this.usuarioByIdUsuarioRecibe;
    }
    
    public void setUsuarioByIdUsuarioRecibe(Usuario usuarioByIdUsuarioRecibe) {
        this.usuarioByIdUsuarioRecibe = usuarioByIdUsuarioRecibe;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


