package POJOs;
// Generated 13-may-2018 13:13:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nomUsuario;
     private String password;
     private String tipoUsuario;
     private String nombre;
     private String apellidos;
     private String email;
     private String localidad;
     private String sexo;
     private String foto;
     private Date ultimoAcceso;
     private Date fechaAlta;
     private Set viajes = new HashSet(0);
     private Set mensajesForIdUsuarioRecibe = new HashSet(0);
     private Set pasajeroses = new HashSet(0);
     private Set puntuacionsForIdUsuarioPuntua = new HashSet(0);
     private Set mensajesForIdUsuarioEnvia = new HashSet(0);
     private Set puntuacionsForIdUsuarioRecibe = new HashSet(0);
     private Set vehiculos = new HashSet(0);
     private Set telefonos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nomUsuario, String password, String tipoUsuario, String nombre, String apellidos, String email, String localidad, String sexo, String foto) {
        this.nomUsuario = nomUsuario;
        this.password = password;
        this.tipoUsuario = tipoUsuario;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.email = email;
        this.localidad = localidad;
        this.sexo = sexo;
        this.foto = foto;
    }
    public Usuario(String nomUsuario, String password, String tipoUsuario, String nombre, String apellidos, String email, String localidad, String sexo, String foto, Date ultimoAcceso, Date fechaAlta, Set viajes, Set mensajesForIdUsuarioRecibe, Set pasajeroses, Set puntuacionsForIdUsuarioPuntua, Set mensajesForIdUsuarioEnvia, Set puntuacionsForIdUsuarioRecibe, Set vehiculos, Set telefonos) {
       this.nomUsuario = nomUsuario;
       this.password = password;
       this.tipoUsuario = tipoUsuario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.localidad = localidad;
       this.sexo = sexo;
       this.foto = foto;
       this.ultimoAcceso = ultimoAcceso;
       this.fechaAlta = fechaAlta;
       this.viajes = viajes;
       this.mensajesForIdUsuarioRecibe = mensajesForIdUsuarioRecibe;
       this.pasajeroses = pasajeroses;
       this.puntuacionsForIdUsuarioPuntua = puntuacionsForIdUsuarioPuntua;
       this.mensajesForIdUsuarioEnvia = mensajesForIdUsuarioEnvia;
       this.puntuacionsForIdUsuarioRecibe = puntuacionsForIdUsuarioRecibe;
       this.vehiculos = vehiculos;
       this.telefonos = telefonos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNomUsuario() {
        return this.nomUsuario;
    }
    
    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Date getUltimoAcceso() {
        return this.ultimoAcceso;
    }
    
    public void setUltimoAcceso(Date ultimoAcceso) {
        this.ultimoAcceso = ultimoAcceso;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }
    public Set getMensajesForIdUsuarioRecibe() {
        return this.mensajesForIdUsuarioRecibe;
    }
    
    public void setMensajesForIdUsuarioRecibe(Set mensajesForIdUsuarioRecibe) {
        this.mensajesForIdUsuarioRecibe = mensajesForIdUsuarioRecibe;
    }
    public Set getPasajeroses() {
        return this.pasajeroses;
    }
    
    public void setPasajeroses(Set pasajeroses) {
        this.pasajeroses = pasajeroses;
    }
    public Set getPuntuacionsForIdUsuarioPuntua() {
        return this.puntuacionsForIdUsuarioPuntua;
    }
    
    public void setPuntuacionsForIdUsuarioPuntua(Set puntuacionsForIdUsuarioPuntua) {
        this.puntuacionsForIdUsuarioPuntua = puntuacionsForIdUsuarioPuntua;
    }
    public Set getMensajesForIdUsuarioEnvia() {
        return this.mensajesForIdUsuarioEnvia;
    }
    
    public void setMensajesForIdUsuarioEnvia(Set mensajesForIdUsuarioEnvia) {
        this.mensajesForIdUsuarioEnvia = mensajesForIdUsuarioEnvia;
    }
    public Set getPuntuacionsForIdUsuarioRecibe() {
        return this.puntuacionsForIdUsuarioRecibe;
    }
    
    public void setPuntuacionsForIdUsuarioRecibe(Set puntuacionsForIdUsuarioRecibe) {
        this.puntuacionsForIdUsuarioRecibe = puntuacionsForIdUsuarioRecibe;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }




}


