package reserva;




/**
 * Reservaanimales generated by hbm2java
 */
public class Reservaanimales  implements java.io.Serializable {


     private Integer id;
     private String identificador;
     private String tipoAnimal;
     private String pais;
     private int precio;
     private String email;

    public Reservaanimales() {
    }

    public Reservaanimales(String identificador, String tipoAnimal, String pais, int precio, String email) {
       this.identificador = identificador;
       this.tipoAnimal = tipoAnimal;
       this.pais = pais;
       this.precio = precio;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }
    public String getTipoAnimal() {
        return this.tipoAnimal;
    }
    
    public void setTipoAnimal(String tipoAnimal) {
        this.tipoAnimal = tipoAnimal;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


